### ISSUE TITLE
需要Netflix的API对接网站

### ISSUE THREAD

**Issue by xsidc** [luolongfei/netflix#1]
您好，我需要1个修改Netlfix密码，重置密码，修改PIN码，重置PIN码等等一些功能，您这边有吗？

**Comment by luolongfei** [comment]
目前是支持修改重置密码，pin 码相关的没有。

**Comment by xsidc** [comment]
需要花钱找你买吗？多少钱？

**Comment by luolongfei** [comment]
@xsidc 目前没有pin相关的功能，可以定制开发，一般情况下，3k起步。但如果你能详细描述你的需求以及应用场景，又正好是我感兴趣的方向的情况下，则价格另议。可以先联系我邮箱 luolongf@gmail.com 详细描述需求。
