### ISSUE TITLE
未识别西班牙语言密码修改邮件

### ISSUE THREAD

**Issue by cxh6qnbb** [luolongfei/netflix#3]
邮件主题:Tu contraseña se ha cambiado
邮件原始文件[Tu contraseña se ha cambiado.zip](https://github.com/luolongfei/netflix/files/7832792/Tu.contrasena.se.ha.cambiado.zip)

**Comment by luolongfei** [comment]
看来不能通过标题来判断，应该根据邮件里的链接地址来判断，等空了调整一下

**Comment by luolongfei** [comment]
刚刚发布了v0.5.4版，现在不再通过邮件标题判断是否密码重置邮件了，而是正则匹配邮件内容里类似 https://www.netflix.com/YourAccount?lnktrk=EMP&g=9E8A183BDD4A0202D0D61F8C368A07FE645701EE&lkid=URL_YOUR_ACCOUNT_2 的地址，命中即说明是密码重置邮件，不再受邮件语言影响。
